# Generated by Django 6.0.4 on 2026-05-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_file',
            field=models.FileField(upload_to='books/', verbose_name='загрузите pdf-файл книги'),
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, upload_to='books/', verbose_name='загрузите обложку в формате jpg или png'),
        ),
        migrations.AlterField(
            model_name='books',
            name='quantity_pages',
            field=models.PositiveIntegerField(default=100, null=True, verbose_name='кол-во страниц'),
        ),
    ]
