# Generated by Django 6.0.4 on 2026-05-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='напишите название книги')),
                ('description', models.TextField(blank=True, verbose_name='напишите аннотацию')),
                ('image', models.ImageField(blank=True, upload_to='books/', verbose_name='загрузите обложку в формате jpg или png')),
                ('book_file', models.FileField(upload_to='books/', verbose_name='загрузите pdf-файл книги')),
                ('quantity_pages', models.PositiveIntegerField(default=100, null=True, verbose_name='кол-во страниц')),
                ('genre', models.CharField(choices=[('Детектив', 'Детектив'), ('Хоррор', 'Хоррор'), ('Классика', 'Классика')], default='Классиказн', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(default='Автор неизвестен', max_length=100, verbose_name='напишите автора')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='укажите цену')),
                ('email_publisher', models.EmailField(max_length=254, null=True, verbose_name='почта издательства')),
                ('views_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
