# Generated by Django 6.0.4 on 2026-05-05 09:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHorse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tourist Name', max_length=100)),
                ('horse_nickname', models.CharField(default='Spirit', max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Elite Horse Tour', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('services', models.ManyToManyField(null=True, to='horse_tour.servicehorse')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1, message='Оценка только от 1 до 5'), django.core.validators.MaxValueValidator(5, message='Оценка только от 1 до 5')])),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='horse_tour.tourcompany')),
                ('tourist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_reviews', to='horse_tour.tourist')),
            ],
        ),
    ]
