# Generated by Django 6.0.4 on 2026-05-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourcompany',
            name='services',
            field=models.ManyToManyField(blank=True, to='horse_tour.servicehorse'),
        ),
    ]
