# Generated by Django 6.0.4 on 2026-05-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Кличка лошади')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('health_status', models.CharField(default='Здоров', max_length=100, verbose_name='Состояние здоровья')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='horses/', verbose_name='Фото')),
            ],
        ),
    ]
