# Generated by Django 6.0.4 on 2026-05-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorseTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='tours/')),
            ],
        ),
        migrations.DeleteModel(
            name='Horse',
        ),
    ]
